/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package seamanifesto;

/**
 *
 * @author TAMOJIT
 */
public class Dashboard extends javax.swing.JFrame {

    /**
     * Creates new form Dashboard
     */
    public Dashboard() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        NewArrivalManifest = new javax.swing.JButton();
        ArrivalManifestAmmendment = new javax.swing.JButton();
        DepartureManifest = new javax.swing.JButton();
        DepartureManifestManagement = new javax.swing.JButton();
        DepartureNotification = new javax.swing.JButton();
        UsernameDisplay = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        NewArrivalManifest.setText("New Arrival Manifest");
        NewArrivalManifest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NewArrivalManifestActionPerformed(evt);
            }
        });

        ArrivalManifestAmmendment.setText("Arrival Manifest Ammendment");
        ArrivalManifestAmmendment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ArrivalManifestAmmendmentActionPerformed(evt);
            }
        });

        DepartureManifest.setText("Departure Manifest");
        DepartureManifest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DepartureManifestActionPerformed(evt);
            }
        });

        DepartureManifestManagement.setText("Departure Manifest Management");
        DepartureManifestManagement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DepartureManifestManagementActionPerformed(evt);
            }
        });

        DepartureNotification.setText("Departure Notification");
        DepartureNotification.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DepartureNotificationActionPerformed(evt);
            }
        });

        UsernameDisplay.setText("Username");

        jLabel1.setText("DASHBOARD");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(DepartureNotification)
                    .addComponent(DepartureManifestManagement)
                    .addComponent(DepartureManifest)
                    .addComponent(ArrivalManifestAmmendment)
                    .addComponent(NewArrivalManifest))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE)
                .addGap(227, 227, 227)
                .addComponent(UsernameDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(101, 101, 101))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(UsernameDisplay))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(35, 35, 35)
                .addComponent(NewArrivalManifest)
                .addGap(18, 18, 18)
                .addComponent(ArrivalManifestAmmendment)
                .addGap(18, 18, 18)
                .addComponent(DepartureManifest)
                .addGap(18, 18, 18)
                .addComponent(DepartureManifestManagement)
                .addGap(18, 18, 18)
                .addComponent(DepartureNotification)
                .addContainerGap(78, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ArrivalManifestAmmendmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ArrivalManifestAmmendmentActionPerformed
        // TODO add your handling code here:
        System.out.println("Arrival manifest ammendment clicked");
    }//GEN-LAST:event_ArrivalManifestAmmendmentActionPerformed

    private void DepartureNotificationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DepartureNotificationActionPerformed
        // TODO add your handling code here:
        System.out.println("Departure Notification clicked");
    }//GEN-LAST:event_DepartureNotificationActionPerformed

    private void NewArrivalManifestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NewArrivalManifestActionPerformed
        // TODO add your handling code here:
        System.out.println("Arrival manifest clicked");
        new NewArrivalManifest().setVisible(true);
    }//GEN-LAST:event_NewArrivalManifestActionPerformed

    private void DepartureManifestManagementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DepartureManifestManagementActionPerformed
        // TODO add your handling code here:
        System.out.println("Departure manifest management clicked");
        new DepartureManifestAmmendment().setVisible(true);
    }//GEN-LAST:event_DepartureManifestManagementActionPerformed

    private void DepartureManifestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DepartureManifestActionPerformed
        // TODO add your handling code here:
        System.out.println("Departure manifest clicked");
        new DepartureManifest().setVisible(true);
    }//GEN-LAST:event_DepartureManifestActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ArrivalManifestAmmendment;
    private javax.swing.JButton DepartureManifest;
    private javax.swing.JButton DepartureManifestManagement;
    private javax.swing.JButton DepartureNotification;
    private javax.swing.JButton NewArrivalManifest;
    private javax.swing.JLabel UsernameDisplay;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
