/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package seamanifesto;

/**
 *
 * @author TAMOJIT
 */
public class Dashboard extends javax.swing.JFrame {

    /**
     * Creates new form Dashboard
     */
    public Dashboard() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        NewArrivalManifest = new javax.swing.JButton();
        ArrivalManifestAmmendment = new javax.swing.JButton();
        DepartureManifest = new javax.swing.JButton();
        DepartureManifestManagement = new javax.swing.JButton();
        DepartureNotification = new javax.swing.JButton();
        UsernameDisplay = new javax.swing.JLabel();
        dashboardlabel = new javax.swing.JLabel();
        SeaEntryInward = new javax.swing.JButton();
        UploadButton = new javax.swing.JButton();

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        NewArrivalManifest.setText("New Arrival Manifest");
        NewArrivalManifest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NewArrivalManifestActionPerformed(evt);
            }
        });

        ArrivalManifestAmmendment.setText("Arrival Manifest Ammendment");
        ArrivalManifestAmmendment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ArrivalManifestAmmendmentActionPerformed(evt);
            }
        });

        DepartureManifest.setText("Departure Manifest");
        DepartureManifest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DepartureManifestActionPerformed(evt);
            }
        });

        DepartureManifestManagement.setText("Departure Manifest Ammendment");
        DepartureManifestManagement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DepartureManifestManagementActionPerformed(evt);
            }
        });

        DepartureNotification.setText("Departure Notification");
        DepartureNotification.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DepartureNotificationActionPerformed(evt);
            }
        });

        UsernameDisplay.setText("Username");

        dashboardlabel.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        dashboardlabel.setText("DASHBOARD");

        SeaEntryInward.setText("Sea Entry Inward");
        SeaEntryInward.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SeaEntryInwardActionPerformed(evt);
            }
        });

        UploadButton.setText("Upload File");
        UploadButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UploadButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(dashboardlabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(97, 97, 97)
                        .addComponent(UsernameDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(165, 165, 165))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(NewArrivalManifest, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(DepartureManifest, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(DepartureNotification, javax.swing.GroupLayout.DEFAULT_SIZE, 295, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(ArrivalManifestAmmendment, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(DepartureManifestManagement, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(SeaEntryInward, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(66, 66, 66))))
            .addGroup(layout.createSequentialGroup()
                .addGap(179, 179, 179)
                .addComponent(UploadButton, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dashboardlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(UsernameDisplay))
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ArrivalManifestAmmendment)
                    .addComponent(NewArrivalManifest))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(DepartureManifestManagement)
                    .addComponent(DepartureManifest))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(DepartureNotification)
                    .addComponent(SeaEntryInward))
                .addGap(18, 18, 18)
                .addComponent(UploadButton)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ArrivalManifestAmmendmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ArrivalManifestAmmendmentActionPerformed
        // TODO add your handling code here:
        System.out.println("Arrival manifest ammendment clicked");
        new ArrivalManifestAmmendment().setVisible(true);
    }//GEN-LAST:event_ArrivalManifestAmmendmentActionPerformed

    private void DepartureNotificationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DepartureNotificationActionPerformed
        // TODO add your handling code here:
        System.out.println("Departure Notification clicked");
        new DepartureNotification().setVisible(true);
    }//GEN-LAST:event_DepartureNotificationActionPerformed

    private void NewArrivalManifestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NewArrivalManifestActionPerformed
        // TODO add your handling code here:
        System.out.println("Arrival manifest clicked");
        new NewArrivalManifest().setVisible(true);
    }//GEN-LAST:event_NewArrivalManifestActionPerformed

    private void DepartureManifestManagementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DepartureManifestManagementActionPerformed
        // TODO add your handling code here:
        System.out.println("Departure manifest management clicked");
        new DepartureManifestAmmendment().setVisible(true);
    }//GEN-LAST:event_DepartureManifestManagementActionPerformed

    private void DepartureManifestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DepartureManifestActionPerformed
        // TODO add your handling code here:
        System.out.println("Departure manifest clicked");
        new DepartureManifest().setVisible(true);
    }//GEN-LAST:event_DepartureManifestActionPerformed

    private void UploadButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UploadButtonActionPerformed
        // TODO add your handling code here:
        System.out.println("Upload UI Clicked");
        new uploadUI().setVisible(true);
        
    }//GEN-LAST:event_UploadButtonActionPerformed

    private void SeaEntryInwardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SeaEntryInwardActionPerformed
        // TODO add your handling code here:
        System.out.println("Entry Inward clicked");
        new EntryInward().setVisible(true);
    }//GEN-LAST:event_SeaEntryInwardActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ArrivalManifestAmmendment;
    private javax.swing.JButton DepartureManifest;
    private javax.swing.JButton DepartureManifestManagement;
    private javax.swing.JButton DepartureNotification;
    private javax.swing.JButton NewArrivalManifest;
    private javax.swing.JButton SeaEntryInward;
    private javax.swing.JButton UploadButton;
    private javax.swing.JLabel UsernameDisplay;
    private javax.swing.JLabel dashboardlabel;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
