package seamanifesto;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Kaustav
 */
public class StartUI extends javax.swing.JFrame {

    /**
     * Creates new form StartUI
     */
    public StartUI() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        bar = new javax.swing.JProgressBar();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        msgLabel = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        version = new java.awt.Label();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        bar.setBackground(new java.awt.Color(255, 255, 255));
        bar.setForeground(new java.awt.Color(51, 255, 51));
        jPanel1.add(bar);
        bar.setBounds(0, 370, 750, 30);

        jLabel4.setFont(new java.awt.Font("Bahnschrift", 1, 24)); // NOI18N
        jLabel4.setText("SEA");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(390, 210, 60, 40);

        jLabel5.setFont(new java.awt.Font("Bahnschrift", 1, 24)); // NOI18N
        jLabel5.setText("MANIFESTO");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(330, 230, 160, 50);

        jLabel7.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        jLabel7.setText("- Drafting Ship Manifests for Customs just became easier");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(190, 290, 360, 20);
        jLabel7.getAccessibleContext().setAccessibleName("Drafting Ship Manifests for Customs just became easier");

        jLabel2.setFont(new java.awt.Font("Lucida Sans Typewriter", 0, 13)); // NOI18N
        jLabel2.setText("Cubefrost-Org/sea-manifesto");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(530, 30, 190, 20);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logo.png"))); // NOI18N
        jLabel1.setToolTipText("");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(210, 170, 120, 120);

        msgLabel.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        jPanel1.add(msgLabel);
        msgLabel.setBounds(10, 330, 480, 30);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cubefrost logo.png"))); // NOI18N
        jPanel1.add(jLabel3);
        jLabel3.setBounds(-10, 10, 270, 110);

        version.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        version.setText("Version 0.1");
        jPanel1.add(version);
        version.setBounds(640, 50, 70, 20);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/github logo.jpg"))); // NOI18N
        jPanel1.add(jLabel6);
        jLabel6.setBounds(490, 20, 30, 40);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 750, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 4, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public int disp(){
        try{
            
        for(int i=0;i<=120;i++){
            Thread.sleep(70);
            this.bar.setValue(i);
            if(i==0)
                msgLabel.setText("Powering up...");
            if(i==30)
                msgLabel.setText("Loading assets... setting sails...");
            if(i==60)
                msgLabel.setText("Checking file systems and stockpiles...");
            if(i==90)
                msgLabel.setText("And here off we go...");
            if(i>=20 && i<=80){
                i+=(int)(Math.random()*5);
            }
        }
        this.dispose();
        return 1;
        }catch(Exception e){
            System.out.println(e.getMessage());
            return 0;
        }
    }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StartUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StartUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StartUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StartUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StartUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JProgressBar bar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel msgLabel;
    private java.awt.Label version;
    // End of variables declaration//GEN-END:variables
}
